### ISSUE TITLE
I can't get Rubban to create index patterns

### ISSUE THREAD

**Issue by sclarke81** [sherifabdlnaby/rubban#6]
Hi, I was wondering if you could help me with where I'm going wrong. I'm using elastdocker 3.2.0 with version 8.5.2. I thought Rubban sounded really useful and have been trying to set it up but it's not creating index patterns for me. I have indexes like:

```
logstash-dev-2022-12-09 
logstash-dev-2022-12-12 
logstash-test-2022-12-09 
```

My `docker-compose.tools.yml` is:

```
version: '3.5'

services:
  rubban:
    image: sherifabdlnaby/rubban:latest
    restart: unless-stopped
    environment:
      RUBBAN_KIBANA_HOST: "https://${KIBANA_HOST}:${KIBANA_PORT}"
      RUBBAN_KIBANA_USER: ${ELASTIC_USERNAME}
      RUBBAN_KIBANA_PASSWORD: ${ELASTIC_PASSWORD}
      RUBBAN_REFRESHINDEXPATTERN_ENABLED: 'true'
      RUBBAN_REFRESHINDEXPATTERN_SCHEDULE: '*/5 * * * *'
      RUBBAN_REFRESHINDEXPATTERN_PATTERNS: '*'
      RUBBAN_AUTOINDEXPATTERN_ENABLED: 'true'
      RUBBAN_AUTOINDEXPATTERN_SCHEDULE: '*/1 * * * *'
      RUBBAN_AUTOINDEXPATTERN_GENERALPATTERNS: '[{"pattern":"logstash-*","timeFieldName":"@timestamp"}]'
```

I've tried various patterns `logstash-*`, `logstash-?-*` and `logstash-*-?`. From the logs it looks like Rubban is running successfully, but it always just says "Successfully created 0 Index Patterns.".

```
elastic-rubban-1  | {"level":"info","ts":1670839006.0726402,"logger":"Rubban","caller":"rubban/rubban.go:52","msg":"Successfully Loaded Configuration"}
elastic-rubban-1  | {"level":"info","ts":1670839006.0726922,"logger":"Rubban","caller":"rubban/rubban.go:135","msg":"Initializing Kibana API client..."}
elastic-rubban-1  | {"level":"info","ts":1670839006.0727115,"logger":"Rubban.api","caller":"kibana/client.go:111","msg":"Testing connection to Kibana API at ***"}
elastic-rubban-1  | {"level":"info","ts":1670839006.089116,"logger":"Rubban.api","caller":"kibana/client.go:128","msg":"Successfully connected to Kibana API ***"}
elastic-rubban-1  | {"level":"info","ts":1670839006.0891774,"logger":"Rubban","caller":"rubban/rubban.go:147","msg":"Validated Initial Connection to Kibana API"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1385114,"logger":"Rubban","caller":"rubban/rubban.go:155","msg":"Determined Kibana Version: 8.5.2"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1386297,"logger":"Rubban","caller":"rubban/rubban.go:102","msg":"Enabled Auto Index Pattern, Loaded 1 General Pattern(s)"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1386523,"logger":"Rubban","caller":"rubban/rubban.go:107","msg":"Enabled Refresh Indices Patterns, Refreshing 1 Pattern(s)"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1386912,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:90","msg":"Registered Auto Index Pattern"}
elastic-rubban-1  | {"level":"info","ts":1670839006.138715,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:90","msg":"Registered Refresh Indices Patterns"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1387486,"logger":"Rubban","caller":"rubban/rubban.go:78","msg":"Starting Rubban..."}
elastic-rubban-1  | {"level":"info","ts":1670839006.1387775,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:36","msg":"Starting scheduler..."}
elastic-rubban-1  | {"level":"info","ts":1670839006.138953,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:43","msg":"Next Auto Index Pattern run at 2022-12-12 09:57:00 +0000 UTC (13 seconds from now)"}
elastic-rubban-1  | {"level":"info","ts":1670839006.1389782,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:43","msg":"Next Refresh Indices Patterns run at 2022-12-12 10:00:00 +0000 UTC (3 minutes from now)"}
elastic-rubban-1  | {"level":"info","ts":1670839020.0003912,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:75","msg":"Running Auto Index Pattern..."}
elastic-rubban-1  | {"level":"info","ts":1670839020.054825,"logger":"Rubban.autoIndexPattern","caller":"autoindexpattern/task.go:55","msg":"Successfully created 0 Index Patterns.","Index Patterns":{}}
elastic-rubban-1  | {"level":"info","ts":1670839020.0549786,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:81","msg":"Finished Auto Index Pattern. (took ≈ 54ms)"}
elastic-rubban-1  | {"level":"info","ts":1670839020.0550067,"logger":"Rubban.scheduler","caller":"rubban/scheduler.go:82","msg":"Next Auto Index Pattern run at 2022-12-12 09:58:00 +0000 UTC (59 seconds from now)"}
```
